export interface IApiResponseUser {
    id: number,
    username: string,
    nickname: string,
    email: string,
    email_verified_at: string,
    phone: string,
    biography: string,
    location: string,
    website: string,
    birthday: string,
    avatar: string,
    type: string,
    created_at: string,
    updated_at: string,
}